/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_1.h"
#include "Clock_1.h"
#include "Motor_OUT1_aliases.h"
#include "Motor_OUT1.h"
#include "Motor_OUT2_aliases.h"
#include "Motor_OUT2.h"
#include "Motor_En_1_aliases.h"
#include "Motor_En_1.h"
#include "QuadDec_1.h"
#include "QuadDec_1_PVT.h"
#include "Motor_IN_1_aliases.h"
#include "Motor_IN_1.h"
#include "Motor_IN_2_aliases.h"
#include "Motor_IN_2.h"
#include "UART_1.h"
#include "QuadDec_1_isr.h"
#include "QuadDec_1_Cnt16.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

